[features]
seeds = false
skip-lint = false
[programs.localnet]
paperpetual_program = "CKGGMgd8CQgJMRhUYjai2F8QwAGKKsaDz559PbUghjbS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/stpkey/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
