[features]
seeds = false
skip-lint = false
[programs.devnet]
paperpetual_program = "EkSeBQi7LrfwoiyGbqBxPMReRN5u9wZuxQ2f72HDaEhP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/stpkey/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
